version: "3"
services:
  Openfire:
    image: gizmotronic/openfire:4.2.3
    restart: always
    volumes:
      - /srv/docker/openfire/openfire:/var/lib/openfire
    networks:
      - roadiniserver_proxynet

  notificationservice:
     image: notservice
     links:
       - Openfire
     command: ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "target/notification-0.0.1-SNAPSHOT.jar"]
     networks:
       - roadiniserver_proxynet
     container_name: notification_service 
  

networks:
    roadiniserver_proxynet:
        external: true

